---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
````{r}
train=read.csv("Competition_Train.csv")
test=read.csv("Competition_Test.csv")
str(train)
summary(train)
str(test)
```

```{r}
train$potential_issue = as.factor(train$potential_issue)
train[18:23] = lapply(train[18:23], as.factor)
str(train)
```


````{r}
library(e1071)
skewness(train$sku)
skewness(train$national_inv)
skewness(train$lead_time)
skewness(train$in_transit_qty)
skewness(train$forecast_3_month)
skewness(train$forecast_6_month)
skewness(train$forecast_9_month)
skewness(train$sales_1_month)
skewness(train$sales_3_month)
skewness(train$sales_6_month)
skewness(train$sales_9_month)
skewness(train$min_bank)

skewness(train$pieces_past_due)
skewness(train$perf_6_month_avg)
skewness(train$perf_12_month_avg)
skewness(train$local_bo_qty)

skewness(train$pieces_past_due)

````


```{r}
library(ggpubr)

```

```{r}
#plot fo skewness in national_inv
qplot(x=national_inv,data=train)
```
```{r}
summary(train$national_inv)
```
```{r}
summary(log10(abs(train$national_inv)+1))
```
```{r}
#plot fo skewness in national_inv
train$national_inv=log10(abs(train$national_inv)+1)
qplot(x=national_inv,data=train)

```
```{r}
qplot(x=lead_time,data=train)
```



```{r}
train$national_inv=log10(abs(train$national_inv)+1)
train$lead_time=log10(abs(train$lead_time)+1)
train$in_transit_qty=log10(abs(train$in_transit_qty)+1)
train$forecast_3_month=log10(abs(train$forecast_3_month)+1)
train$forecast_6_month=log10(abs(train$forecast_6_month)+1)
train$forecast_9_month=log10(abs(train$forecast_9_month)+1)
train$sales_1_month=log10(abs(train$sales_1_month)+1)
train$sales_3_month=log10(abs(train$sales_3_month)+1)
train$sales_6_month=log10(abs(train$sales_6_month)+1)
train$sales_9_month=log10(abs(train$sales_9_month)+1)
train$min_bank=log10(abs(train$min_bank)+1)
train$pieces_past_due=log10(abs(train$pieces_past_due)+1)
train$perf_6_month_avg=log10(abs(train$perf_6_month_avg)+1)
train$perf_12_month_avg=log10(abs(train$perf_12_month_avg)+1)
train$local_bo_qty=log10(abs(train$local_bo_qty)+1)
train$pieces_past_due=log10(abs(train$pieces_past_due)+1)

```

```{r}
skewness(train$sku)
skewness(train$national_inv)
skewness(train$lead_time)
skewness(train$in_transit_qty)
skewness(train$forecast_3_month)
skewness(train$forecast_6_month)
skewness(train$forecast_9_month)
skewness(train$sales_1_month)
skewness(train$sales_3_month)
skewness(train$sales_6_month)
skewness(train$sales_9_month)
skewness(train$min_bank)
skewness(train$pieces_past_due)
skewness(train$perf_6_month_avg)
skewness(train$perf_12_month_avg)
skewness(train$local_bo_qty)
skewness(train$pieces_past_due)

```




```{r}
numericData <- train[sapply(train, is.numeric)]

corr <- round(cor(numericData, use = "pairwise.complete.obs"), 2)
tail(corr)
library(reshape2)
melted_cormat <- melt(corr, na.rm = TRUE)
head(melted_cormat)
library(ggplot2)
ggplot(data = melted_cormat, aes(x = Var1, y = Var2, fill = value)) + geom_tile()
library(ggcorrplot)
ggcorrplot(corr)


```

