---
title: "R Notebook"
output: html_notebook
---

```{r}
train=read.csv("Competition_Train.csv")
test=read.csv("Competition_Test.csv")
str(train)
```

```{r}
train$potential_issue = as.factor(train$potential_issue)
train[18:23] = lapply(train[18:23], as.factor)
str(train)
test$potential_issue = as.factor(test$potential_issue)
test[18:22] = lapply(test[18:22], as.factor)
str(test)
? lapply
```
```{r}
barplot(prop.table(table(train$went_on_backorder)),col=rainbow(2),yrow=c(0,0.7),main="class distribution")
```


```{r}
library(caTools)
library(randomForest)
```


```{r}
ind=sample(2,nrow(train),replace=TRUE,prob=c(0.6,0.4))
train1=train[ind==1,]
train2=train[ind==2,]
```


```{r}

rf <- randomForest(went_on_backorder~.-sku,data=train1)
rf
```

```{r}
library(ROCR)
pred=predict(rf,train1,type="prob")
dim(pred)
```
```{r}
pred[1:20,]
```
```{r}
table(train1$went_on_backorder,pred[,2]>0.5)
```



```{r}
library(ROCR)
pred=prediction(pred[,2],train1$went_on_backorder)
eval=performance(pred,"tpr","fpr")
plot(eval)


```

```{r}
auc=performance(pred,"auc")
auc@y.values[[1]]
```

